title: Qcole22's Insane Blog Empire  # Your blog's headline
email: qcole2257@gmail.com       # For contact forms
description: >-                     # Site meta description
  Devops Engineer.
baseurl: ""                         # Leave blank for root domain
url: "https://qcole22.github.io"    # Your full site URL
LinkedIn: https://www.linkedin.com/in/quentin-rusnell/ # For LinkedIn cards and sharing
github_username: qcole22            # Links back to your profile
theme: minima                       # Default theme; swap to something flashy later




plugins:
  - jekyll-feed                     # Enables RSS for subscribers